name: run

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    name: Build and test the application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: build and test
      run: go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.64
