name: run

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    name: Build and test the application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: build and test
      run: go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...

    - name: install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.50.1

    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run ./... ;

